from typing import Dict

def generate_investment_report(company_name: str, risk_data: Dict, financial_data: Dict) -> str:
    """
    Generates a structured GenAI investment report using risk and financial signals.
    In a real app, this would use LangChain + LLM (Gemini/OpenAI).
    """
    
    report_template = f"""
# INVESTMENT CREDIT REPORT: {company_name.upper()}
**Date:** 2024-03-10
**Classification:** Internal / Confidential

## 1. Executive Summary
{company_name} is a growth-stage enterprise in the manufacturing sector. The current credit assessment indicates a **{risk_data.get('health_score', 'N/A')}/100** financial health score. Based on the analysis of Asset Liability Management and Annual Reports, the entity demonstrates stable operations with a recommendation for **{risk_data.get('recommendation', 'Conditional Approval')}**.

## 2. Financial Analysis
- **Revenue Performance:** Average revenue recorded at {financial_data.get('revenue', 'N/A')} Cr.
- **Profitability:** Net profit margin is approximately {(financial_data.get('profit', 0) / financial_data.get('revenue', 1) * 100):.1f}%.
- **Liquidity:** Current assets of {financial_data.get('total_assets', 'N/A')} Cr against liabilities of {financial_data.get('total_liabilities', 'N/A')} Cr.
- **Debt Profile:** Total debt standing at {financial_data.get('debt', 'N/A')} Cr with a calculated leverage of {risk_data.get('reasoning', '').split('leverage of ')[1].split(' ')[0] if 'leverage' in risk_data.get('reasoning', '') else 'N/A'}.

## 3. SWOT Analysis
### Strengths
- Strong asset backing relative to industry peers.
- Positive cash flow from operations.
### Weaknesses
- Tight interest coverage during expansion phases.
### Opportunities
- Significant upside from South East Asia expansion signals.
### Threats
- Potential regulatory headwinds in environmental compliance.

## 4. Market & Sector Insights
The sector is currently experiencing moderate growth (4.2% YoY). {company_name} is positioned well despite local raw material volatility.

## 5. Loan Recommendation & Reasoning
**Recommendation:** {risk_data.get('recommendation', 'Pending Review')}
**Reasoning:** {risk_data.get('reasoning', 'Manual review required.')}

---
*Report generated by AltCredit AI Intelligence Engine.*
    """
    return report_template.strip()
